# Generated by Django 5.1.6 on 2025-04-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(db_column='asset_id', max_length=255, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(blank=True, db_column='asset_name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'admin"."assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('content_id', models.CharField(db_column='content_id', max_length=255, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(blank=True, db_column='batch_no', max_length=255, null=True)),
                ('serial_id', models.CharField(blank=True, db_column='serial_id', max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='quantity', null=True)),
            ],
            options={
                'db_table': 'operations"."document_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(db_column='employee_id', max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'human_resources"."employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItemData',
            fields=[
                ('inventory_item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('item_management', models.CharField(max_length=50)),
                ('item_management_id', models.CharField(max_length=255)),
                ('current_quantity', models.IntegerField()),
                ('shelf_life', models.CharField(max_length=50)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('warehouse_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inventory"."vw_inventory_item_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='item_master_data',
            fields=[
                ('item_id', models.CharField(db_column='item_id', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'admin"."item_master_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sales"."order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(db_column='product_id', max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, db_column='product_name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'admin"."products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='productDocument',
            fields=[
                ('productdocu_id', models.CharField(db_column='productdocu_id', max_length=255, primary_key=True, serialize=False)),
                ('expiry_date', models.DateField(auto_now_add=True, db_column='expiry_date')),
            ],
            options={
                'db_table': 'operations"."product_document_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'purchasing"."purchase_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('material_id', models.CharField(db_column='material_id', max_length=255, primary_key=True, serialize=False)),
                ('material_name', models.CharField(blank=True, db_column='material_name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'admin"."raw_materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseMovement',
            fields=[
                ('movement_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('movement_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'inventory"."warehouse_movement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('warehouse_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'admin"."warehouse',
            },
        ),
    ]
