# Generated by Django 5.1.6 on 2025-04-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_stockflow', '0001_initial'),
    ]

    operations = [
    ]
