# Generated by Django 5.1.6 on 2025-04-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_stockflow', '0002_auto_20250416_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('inventory_item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inventory"."inventory_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseMovementData',
            fields=[
                ('movement_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('movement_date', models.DateTimeField()),
                ('source_location', models.CharField(max_length=255)),
                ('destination_location', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('movement_status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inventory"."vw_warehouse_movement_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseMovementItem',
            fields=[
                ('warehouse_movement_items_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory"."warehouse_movement_items',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='DocumentItem',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='item_master_data',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='productDocument',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='RawMaterial',
        ),
    ]
