# Generated by Django 5.1.6 on 2025-04-13 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(db_column='asset_id', max_length=255, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(db_column='asset_name', max_length=255)),
                ('purchase_date', models.DateField(blank=True, db_column='purchase_date', null=True)),
                ('serial_no', models.CharField(blank=True, db_column='serial_no', max_length=255, null=True)),
                ('purchased_price', models.DecimalField(blank=True, db_column='purchase_price', decimal_places=2, max_digits=10, null=True)),
                ('content_id', models.CharField(blank=True, db_column='content_id', max_length=255, null=True)),
            ],
            options={
                'db_table': 'assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItemData',
            fields=[
                ('inventory_item_id', models.CharField(db_column='inventory_item_id', max_length=255, primary_key=True, serialize=False)),
                ('serial_id', models.CharField(blank=True, db_column='serial_id', max_length=255, null=True)),
                ('productdocu_id', models.CharField(blank=True, db_column='productdocu_id', max_length=255, null=True)),
                ('item_type', models.CharField(db_column='item_type', max_length=50)),
                ('current_quantity', models.IntegerField(db_column='current_quantity')),
                ('warehouse_id', models.CharField(blank=True, db_column='warehouse_id', max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='date_created')),
            ],
            options={
                'db_table': 'inventory_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemMasterData',
            fields=[
                ('item_id', models.CharField(db_column='item_id', max_length=255, primary_key=True, serialize=False)),
                ('item_type', models.CharField(blank=True, db_column='item_type', max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, db_column='item_name', max_length=255, null=True)),
                ('unit_of_measure', models.CharField(blank=True, db_column='unit_of_measure', max_length=50, null=True)),
                ('manage_item_by', models.CharField(blank=True, db_column='manage_item_by', max_length=100, null=True)),
                ('item_status', models.CharField(blank=True, db_column='item_status', max_length=50, null=True)),
                ('preferred_vendor', models.CharField(blank=True, db_column='preferred_vendor', max_length=255, null=True)),
                ('purchasing_uom', models.CharField(blank=True, db_column='purchasing_uom', max_length=50, null=True)),
                ('items_per_purchase_unit', models.IntegerField(blank=True, db_column='items_per_purchase_unit', null=True)),
                ('purchase_quantity_per_package', models.IntegerField(blank=True, db_column='purchase_quantity_per_package', null=True)),
                ('sales_uom', models.CharField(blank=True, db_column='sales_uom', max_length=50, null=True)),
                ('items_per_sale_unit', models.IntegerField(blank=True, db_column='items_per_sale_unit', null=True)),
                ('sales_quantity_per_package', models.IntegerField(blank=True, db_column='sales_quantity_per_package', null=True)),
            ],
            options={
                'db_table': 'item_master_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItemThreshold',
            fields=[
                ('inventory_item_threshold_id', models.CharField(db_column='inventory_item_threshold_id', max_length=255, primary_key=True, serialize=False)),
                ('minimum_threshold', models.IntegerField(db_column='minimum_threshold')),
                ('maximum_threshold', models.IntegerField(db_column='maximum_threshold')),
            ],
            options={
                'db_table': 'inventory_item_threshold',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(db_column='product_id', max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='product_name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('selling_price', models.DecimalField(blank=True, db_column='selling_price', decimal_places=2, max_digits=10, null=True)),
                ('stock_level', models.IntegerField(blank=True, db_column='stock_level', null=True)),
                ('warranty_period', models.IntegerField(blank=True, db_column='warranty_period', null=True)),
                ('policy_id', models.CharField(blank=True, db_column='policy_id', max_length=255, null=True)),
                ('batch_no', models.CharField(blank=True, db_column='batch_no', max_length=255, null=True)),
                ('item_status', models.CharField(blank=True, db_column='item_status', max_length=50, null=True)),
                ('content_id', models.CharField(blank=True, db_column='content_id', max_length=255, null=True)),
                ('unit_of_measure', models.CharField(blank=True, db_column='unit_of_measure', max_length=50, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase_requests',
            fields=[
                ('request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_date', models.DateField(blank=True, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseQuotation',
            fields=[
                ('quotation_id', models.CharField(db_column='quotation_id', max_length=255, primary_key=True, serialize=False)),
                ('vendor_id', models.CharField(blank=True, db_column='vendor_id', max_length=255, null=True)),
            ],
            options={
                'db_table': 'purchase_quotation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationContent',
            fields=[
                ('quotation_content_id', models.CharField(db_column='quotation_content_id', max_length=255, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(blank=True, db_column='unit_price', decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, db_column='discount', decimal_places=2, max_digits=10, null=True)),
                ('tax_code', models.CharField(blank=True, db_column='tax_code', max_length=50, null=True)),
                ('total', models.DecimalField(blank=True, db_column='total', decimal_places=2, max_digits=10, null=True)),
                ('purchase_quantity', models.IntegerField(blank=True, db_column='purchase_quantity', null=True)),
            ],
            options={
                'db_table': 'quotation_contents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('material_id', models.CharField(db_column='material_id', max_length=255, primary_key=True, serialize=False)),
                ('material_name', models.CharField(db_column='material_name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('unit_of_measure', models.CharField(blank=True, db_column='unit_of_measure', max_length=50, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, db_column='cost_per_unit', decimal_places=2, max_digits=10, null=True)),
                ('vendor_code', models.CharField(blank=True, db_column='vendor_code', max_length=255, null=True)),
            ],
            options={
                'db_table': 'raw_materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItemDataLegacy',
            fields=[
                ('admin_item', models.OneToOneField(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock_manager.itemmasterdata')),
                ('minimum_threshold', models.IntegerField(blank=True, db_column='minimum_threshold', null=True)),
                ('maximum_threshold', models.IntegerField(blank=True, db_column='maximum_threshold', null=True)),
                ('total_stock', models.IntegerField(blank=True, db_column='total_stock', null=True)),
                ('available_stock', models.IntegerField(blank=True, db_column='available_stock', null=True)),
                ('last_update', models.DateTimeField(blank=True, db_column='last_update', null=True)),
            ],
            options={
                'db_table': 'inventory_item_data',
                'managed': False,
            },
        ),
    ]
