# Generated by Django 5.1.6 on 2025-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMasterData',
            fields=[
                ('item_md_id', models.CharField(db_column='item_md_id', max_length=50, primary_key=True, serialize=False)),
                ('unit_cost', models.DecimalField(blank=True, db_column='unit_cost', decimal_places=2, max_digits=10, null=True)),
                ('minimum_threshold', models.IntegerField(blank=True, db_column='minimum_threshold', null=True)),
                ('maximum_threshold', models.IntegerField(blank=True, db_column='maximum_threshold', null=True)),
                ('total_stock', models.IntegerField(blank=True, db_column='total_stock', null=True)),
                ('stock_on_order', models.IntegerField(blank=True, db_column='stock_on_order', null=True)),
                ('stock_committed', models.IntegerField(blank=True, db_column='stock_committed', null=True)),
                ('available_stock', models.IntegerField(blank=True, db_column='available_stock', null=True)),
                ('last_update', models.DateTimeField(blank=True, db_column='last_update', null=True)),
            ],
            options={
                'db_table': 'item_master_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(db_column='product_id', max_length=255, primary_key=True, serialize=False)),
                ('item_id', models.CharField(blank=True, db_column='item_id', max_length=255, null=True, unique=True)),
                ('product_name', models.CharField(db_column='product_name', max_length=255)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
