# Generated by Django 5.1.6 on 2025-04-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItemDataLegacy',
        ),
    ]
