# Generated by Django 5.1.6 on 2025-03-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemmasterdata',
            table='inventory_item_master_data',
        ),
    ]
