# Generated by Django 5.1.6 on 2025-04-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0002_delete_inventoryitemdatalegacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventoryView',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stock_committed', models.IntegerField()),
                ('total_stock', models.IntegerField()),
                ('available_stock', models.IntegerField()),
                ('minimum_threshold', models.IntegerField()),
                ('maximum_threshold', models.IntegerField()),
                ('last_update', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'vw_inventory_product_data',
                'managed': False,
            },
        ),
    ]
