# Generated by Django 5.1.6 on 2025-04-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0003_productinventoryview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInventoryView',
            fields=[
                ('asset_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stock_committed', models.IntegerField(default=0)),
                ('stock_on_order', models.IntegerField(default=0)),
                ('total_stock', models.IntegerField(default=0)),
                ('available_stock', models.IntegerField(default=0)),
                ('minimum_threshold', models.IntegerField(default=0)),
                ('maximum_threshold', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_inventory_asset_data',
                'managed': False,
            },
        ),
    ]
