# Generated by Django 5.1.6 on 2025-03-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0003_assets_raw_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminItemMasterData',
            fields=[
                ('item_id', models.CharField(db_column='item_id', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'item_master_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItemMasterData',
            fields=[
                ('item_md_id', models.CharField(db_column='item_md_id', max_length=255, primary_key=True, serialize=False)),
                ('minimum_threshold', models.IntegerField(blank=True, db_column='minimum_threshold', null=True)),
                ('maximum_threshold', models.IntegerField(blank=True, db_column='maximum_threshold', null=True)),
                ('total_stock', models.IntegerField(blank=True, db_column='total_stock', null=True)),
                ('stock_on_order', models.IntegerField(blank=True, db_column='stock_on_order', null=True)),
                ('stock_committed', models.IntegerField(blank=True, db_column='stock_committed', null=True)),
                ('available_stock', models.IntegerField(blank=True, db_column='available_stock', null=True)),
                ('last_update', models.DateTimeField(blank=True, db_column='last_update', null=True)),
            ],
            options={
                'db_table': 'inventory_item_master_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ItemMasterData',
        ),
    ]
