# Generated by Django 5.1.6 on 2025-03-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0004_adminitemmasterdata_inventoryitemmasterdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('approval_id', models.IntegerField(blank=True, null=True)),
                ('purchase_item', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_description', models.TextField(blank=True, null=True)),
                ('purchase_quantity', models.IntegerField(blank=True, null=True)),
                ('valid_date', models.DateField(blank=True, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_requests',
                'managed': False,
            },
        ),
    ]
