# Generated by Django 5.1.6 on 2025-04-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0005_rawmaterialinventoryview'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='"admin"."assets"',
        ),
        migrations.AlterModelTable(
            name='assetinventoryview',
            table='"public"."vw_inventory_asset_data"',
        ),
        migrations.AlterModelTable(
            name='inventoryitemdata',
            table='"inventory"."inventory_item"',
        ),
        migrations.AlterModelTable(
            name='inventoryitemthreshold',
            table='"inventory"."inventory_item_threshold"',
        ),
        migrations.AlterModelTable(
            name='itemmasterdata',
            table='"admin"."item_master_data"',
        ),
        migrations.AlterModelTable(
            name='product',
            table='"admin"."products"',
        ),
        migrations.AlterModelTable(
            name='productinventoryview',
            table='"public"."vw_inventory_product_data"',
        ),
        migrations.AlterModelTable(
            name='purchase_requests',
            table='"purchasing"."purchase_requests"',
        ),
        migrations.AlterModelTable(
            name='purchasequotation',
            table='"purchasing"."purchase_quotation"',
        ),
        migrations.AlterModelTable(
            name='quotationcontent',
            table='"purchasing"."quotation_contents"',
        ),
        migrations.AlterModelTable(
            name='rawmaterial',
            table='"admin"."raw_materials"',
        ),
        migrations.AlterModelTable(
            name='rawmaterialinventoryview',
            table='"public"."vw_inventory_material_data"',
        ),
    ]
