# Generated by Django 5.1.6 on 2025-03-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0006_purchase_requests_delete_purchaserequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase_requests',
        ),
    ]
