# Generated by Django 5.1.6 on 2025-05-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0006_alter_asset_table_alter_assetinventoryview_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('inventory_item_id', models.CharField(db_column='inventory_item_id', max_length=255, primary_key=True, serialize=False)),
                ('item_type', models.CharField(db_column='item_type', max_length=50)),
                ('current_quantity', models.IntegerField(db_column='current_quantity')),
                ('warehouse_id', models.CharField(blank=True, db_column='warehouse_id', max_length=255, null=True)),
                ('expiry', models.DateTimeField(blank=True, db_column='expiry', null=True)),
                ('shelf_life', models.CharField(blank=True, db_column='shelf_life', max_length=50, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, db_column='last_update')),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='date_created')),
                ('item_no', models.CharField(blank=True, db_column='item_no', max_length=255, null=True, unique=True)),
                ('start_of_depreciation', models.DateTimeField(blank=True, db_column='start_of_depreciation', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_demo_item', models.BooleanField(db_column='is_demo_item', default=False)),
            ],
            options={
                'db_table': '"inventory"."inventory_item"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseAllItemStockView',
            fields=[
                ('id', models.CharField(max_length=511, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=255)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('warehouse_id', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=50)),
                ('total_stock', models.IntegerField(default=0)),
                ('stock_committed', models.IntegerField(default=0)),
                ('available_stock', models.IntegerField(default=0)),
                ('stock_on_order', models.IntegerField(default=0)),
                ('minimum_threshold', models.IntegerField(default=0)),
                ('maximum_threshold', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('earliest_expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"inventory"."vw_warehouse_all_item_stock"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseAssetStockView',
            fields=[
                ('id', models.CharField(max_length=511, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=255)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('warehouse_id', models.CharField(max_length=255)),
                ('total_stock', models.IntegerField(default=0)),
                ('stock_on_order', models.IntegerField(default=0)),
                ('minimum_threshold', models.IntegerField(default=0)),
                ('maximum_threshold', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"inventory"."vw_warehouse_asset_stock"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseMaterialStockView',
            fields=[
                ('id', models.CharField(max_length=511, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=255)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('warehouse_id', models.CharField(max_length=255)),
                ('total_stock', models.IntegerField(default=0)),
                ('stock_on_order', models.IntegerField(default=0)),
                ('minimum_threshold', models.IntegerField(default=0)),
                ('maximum_threshold', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('earliest_expiry', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"inventory"."vw_warehouse_material_stock"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseProductStockView',
            fields=[
                ('id', models.CharField(max_length=511, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=255)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('warehouse_id', models.CharField(max_length=255)),
                ('total_stock', models.IntegerField(default=0)),
                ('stock_committed', models.IntegerField(default=0)),
                ('available_stock', models.IntegerField(default=0)),
                ('minimum_threshold', models.IntegerField(default=0)),
                ('maximum_threshold', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"inventory"."vw_warehouse_product_stock"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='InventoryItemData',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='RawMaterial',
        ),
        migrations.AlterModelTable(
            name='assetinventoryview',
            table='"inventory"."vw_inventory_asset_data"',
        ),
        migrations.AlterModelTable(
            name='productinventoryview',
            table='"inventory"."vw_inventory_product_data"',
        ),
        migrations.AlterModelTable(
            name='rawmaterialinventoryview',
            table='"inventory"."vw_inventory_material_data"',
        ),
    ]
