# Generated by Django 5.1.6 on 2025-03-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0007_delete_purchase_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_requests',
            fields=[
                ('request_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, db_column='employee', max_length=255, null=True)),
                ('approval_id', models.CharField(blank=True, max_length=255, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_item', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_description', models.TextField(blank=True, null=True)),
                ('purchase_quantity', models.IntegerField(blank=True, null=True)),
                ('valid_date', models.DateField(blank=True, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('required_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_requests',
                'managed': False,
            },
        ),
    ]
