# Generated by Django 5.1.6 on 2025-03-30 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0008_purchase_requests'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventoryitemmasterdata',
            table='inventory_product_data',
        ),
    ]
