# Generated by Django 5.1.6 on 2025-03-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0010_inventoryitemdata_inventoryproductdata_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventoryitemdata',
            table='inventory_item',
        ),
    ]
