# Generated by Django 5.1.6 on 2025-04-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyclicCount',
            fields=[
                ('inventory_count_id', models.CharField(db_column='inventory_count_id', max_length=255, primary_key=True, serialize=False)),
                ('item_onhand', models.IntegerField(blank=True, db_column='item_onhand', null=True)),
                ('item_actually_counted', models.IntegerField(blank=True, db_column='item_actually_counted', null=True)),
                ('difference_in_qty', models.IntegerField(blank=True, db_column='difference_in_qty', null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Open', 'Open'), ('Closed', 'Closed')], db_column='status', max_length=20)),
                ('remarks', models.TextField(blank=True, db_column='remarks', null=True)),
                ('time_period', models.CharField(blank=True, db_column='time_period', max_length=50, null=True)),
            ],
            options={
                'db_table': 'inventory_cyclic_counts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(db_column='employee_id', max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', max_length=100)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('inventory_item_id', models.CharField(db_column='inventory_item_id', max_length=255, primary_key=True, serialize=False)),
                ('serial_id', models.CharField(blank=True, db_column='serial_id', max_length=255, null=True)),
                ('productdocu_id', models.CharField(blank=True, db_column='productdocu_id', max_length=255, null=True)),
                ('material_id', models.CharField(blank=True, db_column='material_id', max_length=255, null=True)),
                ('asset_id', models.CharField(blank=True, db_column='asset_id', max_length=255, null=True)),
                ('item_type', models.CharField(db_column='item_type', max_length=50)),
                ('current_quantity', models.IntegerField(db_column='current_quantity')),
                ('warehouse_id', models.CharField(blank=True, db_column='warehouse_id', max_length=255, null=True)),
                ('date_created', models.DateTimeField(db_column='date_created', editable=False)),
            ],
            options={
                'db_table': 'inventory_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItemThreshold',
            fields=[
                ('inventory_item_threshold_id', models.CharField(db_column='inventory_item_threshold_id', max_length=50, primary_key=True, serialize=False)),
                ('minimum_threshold', models.IntegerField(db_column='minimum_threshold')),
                ('maximum_threshold', models.IntegerField(db_column='maximum_threshold')),
            ],
            options={
                'db_table': 'inventory_item_threshold',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemMasterData',
            fields=[
                ('item_id', models.CharField(db_column='item_id', max_length=255, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(blank=True, db_column='asset_id', max_length=255, null=True)),
                ('material_id', models.CharField(blank=True, db_column='material_id', max_length=255, null=True)),
                ('item_type', models.CharField(blank=True, db_column='item_type', max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, db_column='item_name', max_length=255, null=True)),
                ('unit_of_measure', models.CharField(blank=True, db_column='unit_of_measure', max_length=50, null=True)),
                ('manage_item_by', models.CharField(blank=True, db_column='manage_item_by', max_length=100, null=True)),
                ('item_status', models.CharField(blank=True, db_column='item_status', max_length=50, null=True)),
                ('preferred_vendor', models.CharField(blank=True, db_column='preferred_vendor', max_length=255, null=True)),
                ('purchasing_uom', models.CharField(blank=True, db_column='purchasing_uom', max_length=50, null=True)),
                ('items_per_purchase_unit', models.IntegerField(blank=True, db_column='items_per_purchase_unit', null=True)),
                ('purchase_quantity_per_package', models.IntegerField(blank=True, db_column='purchase_quantity_per_package', null=True)),
                ('sales_uom', models.CharField(blank=True, db_column='sales_uom', max_length=50, null=True)),
                ('items_per_sale_unit', models.IntegerField(blank=True, db_column='items_per_sale_unit', null=True)),
                ('sales_quantity_per_package', models.IntegerField(blank=True, db_column='sales_quantity_per_package', null=True)),
            ],
            options={
                'db_table': 'item_master_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(db_column='product_id', max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='product_name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('selling_price', models.DecimalField(blank=True, db_column='selling_price', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
