# Generated by Django 5.1.6 on 2025-03-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyclicCount',
            fields=[
                ('inventory_count_id', models.AutoField(db_column='inventory_count_id', primary_key=True, serialize=False)),
                ('item_onhand', models.IntegerField(blank=True, db_column='item_onhand', null=True)),
                ('item_actually_counted', models.IntegerField(blank=True, db_column='item_actually_counted', null=True)),
                ('difference_in_qty', models.IntegerField(blank=True, db_column='difference_in_qty', null=True)),
                ('status', models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('In-review', 'In-review')], db_column='status', max_length=20)),
                ('remarks', models.TextField(blank=True, db_column='remarks', null=True)),
                ('time_period', models.CharField(blank=True, db_column='time_period', max_length=50, null=True)),
            ],
            options={
                'db_table': 'inventory.inventory_cyclic_counts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(db_column='employee_id', max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', max_length=100)),
            ],
            options={
                'db_table': 'human_resources.employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemMasterData',
            fields=[
                ('item_id', models.CharField(db_column='item_id', max_length=50, primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='item_name', max_length=200)),
            ],
            options={
                'db_table': 'admin.item_master_data',
                'managed': False,
            },
        ),
    ]
