# Generated by Django 5.1.6 on 2025-03-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cycliccount',
            table='inventory_cyclic_counts',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
    ]
