# Generated by Django 5.1.6 on 2025-04-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cycliccount',
            table='inventory.inventory_cyclic_counts',
        ),
        migrations.AlterModelTable(
            name='inventoryitem',
            table='inventory.inventory_item',
        ),
    ]
