# Generated by Django 5.1.6 on 2025-04-13 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0002_alter_cycliccount_table_alter_inventoryitem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cycliccount',
            table='inventory_cyclic_counts',
        ),
        migrations.AlterModelTable(
            name='inventoryitem',
            table='inventory_item',
        ),
    ]
