# Generated by Django 5.1.6 on 2025-03-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0002_alter_cycliccount_table_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemmasterdata',
            table='item_master_data',
        ),
    ]
