# Generated by Django 5.1.6 on 2025-03-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0003_alter_itemmasterdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(db_column='product_id', max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='product_name', max_length=200)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ItemMasterData',
        ),
    ]
