# Generated by Django 5.1.6 on 2025-04-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0003_alter_cycliccount_table_alter_inventoryitem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='human_resources.employees',
        ),
    ]
