# Generated by Django 5.1.6 on 2025-04-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0004_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
    ]
