# Generated by Django 5.1.6 on 2025-03-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0005_products_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMasterData',
            fields=[
                ('item_md_id', models.CharField(db_column='item_md_id', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'item_master_data',
                'managed': False,
            },
        ),
    ]
