# Generated by Django 5.1.6 on 2025-03-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0006_itemmasterdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itemmasterdata',
            table='inventory_item_master_data',
        ),
    ]
