# Generated by Django 5.1.6 on 2025-04-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0006_alter_cycliccount_table_alter_inventoryitem_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cycliccount',
            table='inventory.inventory_cyclic_counts',
        ),
        migrations.AlterModelTable(
            name='inventoryitem',
            table='inventory.inventory_item',
        ),
        migrations.AlterModelTable(
            name='inventoryitemthreshold',
            table='inventory.inventory_item_threshold',
        ),
    ]
