# Generated by Django 5.1.6 on 2025-03-30 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0007_alter_itemmasterdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('product', models.OneToOneField(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pcounts.products', to_field='item_id')),
                ('minimum_threshold', models.IntegerField(db_column='minimum_threshold', default=0)),
                ('maximum_threshold', models.IntegerField(db_column='maximum_threshold', default=0)),
                ('total_stock', models.IntegerField(db_column='total_stock', default=0)),
                ('available_stock', models.IntegerField(db_column='available_stock', default=0)),
                ('last_update', models.DateTimeField(auto_now_add=True, db_column='last_update')),
            ],
            options={
                'db_table': 'inventory_item',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ItemMasterData',
        ),
    ]
