# Generated by Django 5.1.6 on 2025-03-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0008_inventoryitem_delete_itemmasterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('product_data_id', models.CharField(db_column='item_md_id', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inventory_product_data',
                'managed': False,
            },
        ),
    ]
