# Generated by Django 5.1.6 on 2025-05-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0008_alter_cycliccount_table_alter_inventoryitem_table_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterModelTable(
            name='cycliccount',
            table='inventory.inventory_cyclic_counts',
        ),
        migrations.AlterModelTable(
            name='inventoryitem',
            table='inventory.inventory_item',
        ),
        migrations.AlterModelTable(
            name='inventoryitemthreshold',
            table='inventory.inventory_item_threshold',
        ),
    ]
