# Generated by Django 5.1.6 on 2025-05-06 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0009_delete_employee_alter_cycliccount_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cycliccount',
            table='inventory"."inventory_cyclic_counts',
        ),
        migrations.AlterModelTable(
            name='inventoryitem',
            table='inventory"."inventory_item',
        ),
        migrations.AlterModelTable(
            name='inventoryitemthreshold',
            table='inventory"."inventory_item_threshold',
        ),
        migrations.AlterModelTable(
            name='itemmasterdata',
            table='admin"."item_master_data',
        ),
    ]
