# Generated by Django 5.1.6 on 2025-04-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcounts', '0009_productdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMasterData',
            fields=[
                ('item_id', models.CharField(db_column='item_id', max_length=255, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(blank=True, db_column='asset_id', max_length=255, null=True)),
                ('material_id', models.CharField(blank=True, db_column='material_id', max_length=255, null=True)),
                ('item_type', models.CharField(blank=True, db_column='item_type', max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, db_column='item_name', max_length=255, null=True)),
                ('unit_of_measure', models.CharField(blank=True, db_column='unit_of_measure', max_length=50, null=True)),
                ('manage_item_by', models.CharField(blank=True, db_column='manage_item_by', max_length=100, null=True)),
                ('item_status', models.CharField(blank=True, db_column='item_status', max_length=50, null=True)),
                ('preferred_vendor', models.CharField(blank=True, db_column='preferred_vendor', max_length=255, null=True)),
                ('purchasing_uom', models.CharField(blank=True, db_column='purchasing_uom', max_length=50, null=True)),
                ('items_per_purchase_unit', models.IntegerField(blank=True, db_column='items_per_purchase_unit', null=True)),
                ('purchase_quantity_per_package', models.IntegerField(blank=True, db_column='purchase_quantity_per_package', null=True)),
                ('sales_uom', models.CharField(blank=True, db_column='sales_uom', max_length=50, null=True)),
                ('items_per_sale_unit', models.IntegerField(blank=True, db_column='items_per_sale_unit', null=True)),
                ('sales_quantity_per_package', models.IntegerField(blank=True, db_column='sales_quantity_per_package', null=True)),
            ],
            options={
                'db_table': 'item_master_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(db_column='product_id', max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='product_name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('selling_price', models.DecimalField(blank=True, db_column='selling_price', decimal_places=2, max_digits=10, null=True)),
                ('stock_level', models.IntegerField(blank=True, db_column='stock_level', null=True)),
                ('warranty_period', models.IntegerField(blank=True, db_column='warranty_period', null=True)),
                ('policy_id', models.CharField(blank=True, db_column='policy_id', max_length=255, null=True)),
                ('batch_no', models.CharField(blank=True, db_column='batch_no', max_length=255, null=True)),
                ('item_status', models.CharField(blank=True, db_column='item_status', max_length=50, null=True)),
                ('content_id', models.CharField(blank=True, db_column='content_id', max_length=255, null=True)),
                ('unit_of_measure', models.CharField(blank=True, db_column='unit_of_measure', max_length=50, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
