# Generated by Django 5.1.6 on 2025-04-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.CharField(db_column='asset_id', max_length=255, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(blank=True, db_column='asset_name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'admin"."assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeprecationReport',
            fields=[
                ('deprecation_report_id', models.CharField(db_column='deprecation_report_id', max_length=255, primary_key=True, serialize=False)),
                ('reported_date', models.DateTimeField(auto_now_add=True, db_column='reported_date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_column='status', max_length=20)),
            ],
            options={
                'db_table': 'inventory"."deprecation_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('content_id', models.CharField(db_column='content_id', max_length=255, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='quantity', null=True)),
            ],
            options={
                'db_table': 'operations"."document_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(db_column='employee_id', max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'human_resources"."employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='inventory_items',
            fields=[
                ('inventory_item_id', models.CharField(db_column='inventory_item_id', max_length=255, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True, db_column='last_update')),
                ('item_type', models.CharField(blank=True, db_column='item_type', max_length=255, null=True)),
                ('current_quantity', models.IntegerField(blank=True, db_column='current_quantity', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='date_created')),
                ('expiry', models.DateField(db_column='expiry')),
                ('shelf_life', models.CharField(blank=True, db_column='shelf_life', max_length=20, null=True)),
            ],
            options={
                'db_table': 'inventory"."inventory_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='item_master_data',
            fields=[
                ('item_id', models.CharField(db_column='item_id', max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'admin"."item_master_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(db_column='product_id', max_length=255, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, db_column='product_name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'admin"."products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='productDocument',
            fields=[
                ('productdocu_id', models.CharField(db_column='productdocu_id', max_length=255, primary_key=True, serialize=False)),
                ('expiry_date', models.DateField(auto_now_add=True, db_column='expiry_date')),
            ],
            options={
                'db_table': 'operations"."product_document_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('material_id', models.CharField(db_column='material_id', max_length=255, primary_key=True, serialize=False)),
                ('material_name', models.CharField(blank=True, db_column='material_name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'admin"."raw_materials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='serial_tracking',
            fields=[
                ('serial_id', models.CharField(db_column='serial_id', max_length=255, primary_key=True, serialize=False)),
                ('serial_no', models.CharField(blank=True, db_column='serial_no', max_length=255, null=True)),
            ],
            options={
                'db_table': 'operations"."serial_tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('warehouse_id', models.CharField(db_column='warehouse_id', max_length=255, primary_key=True, serialize=False)),
                ('warehouse_location', models.CharField(blank=True, db_column='warehouse_location', max_length=255, null=True)),
            ],
            options={
                'db_table': 'admin"."warehouse',
                'managed': False,
            },
        ),
    ]
