# Generated by Django 5.1.6 on 2025-04-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_depreciation_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'inventory"."vw_expiry_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryItemData',
            fields=[
                ('inventory_item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=255)),
                ('item_management', models.CharField(max_length=50)),
                ('item_management_id', models.CharField(max_length=255)),
                ('current_quantity', models.IntegerField()),
                ('shelf_life', models.CharField(max_length=50)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('warehouse_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inventory"."vw_inventory_item_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DeprecationReport',
        ),
    ]
