# Generated by Django 5.1.6 on 2025-05-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_depreciation_report', '0002_expiryreport_inventoryitemdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryReportData',
            fields=[
                ('expiry_report_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=50)),
                ('item_management', models.CharField(max_length=50)),
                ('item_no', models.CharField(max_length=255)),
                ('expiry', models.DateTimeField()),
                ('current_quantity', models.IntegerField()),
                ('expiry_report_status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'inventory"."vw_expiry_report_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='DocumentItem',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='ExpiryReport',
        ),
        migrations.DeleteModel(
            name='inventory_items',
        ),
        migrations.DeleteModel(
            name='item_master_data',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='productDocument',
        ),
        migrations.DeleteModel(
            name='RawMaterial',
        ),
        migrations.DeleteModel(
            name='serial_tracking',
        ),
        migrations.DeleteModel(
            name='warehouse',
        ),
    ]
