# Generated by Django 5.1.6 on 2025-03-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0002_alter_itemmasterdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('asset_id', models.CharField(db_column='asset_id', max_length=255, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(db_column='asset_name', max_length=255)),
            ],
            options={
                'db_table': 'assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raw_materials',
            fields=[
                ('material_id', models.CharField(db_column='material_id', max_length=255, primary_key=True, serialize=False)),
                ('material_name', models.CharField(db_column='material_name', max_length=255)),
            ],
            options={
                'db_table': 'raw_materials',
                'managed': False,
            },
        ),
    ]
