# Generated by Django 5.1.6 on 2025-03-30 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0009_alter_inventoryitemmasterdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemData',
            fields=[
                ('admin_item', models.OneToOneField(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock_manager.adminitemmasterdata')),
                ('minimum_threshold', models.IntegerField(blank=True, db_column='minimum_threshold', null=True)),
                ('maximum_threshold', models.IntegerField(blank=True, db_column='maximum_threshold', null=True)),
                ('total_stock', models.IntegerField(blank=True, db_column='total_stock', null=True)),
                ('available_stock', models.IntegerField(blank=True, db_column='available_stock', null=True)),
                ('last_update', models.DateTimeField(blank=True, db_column='last_update', null=True)),
            ],
            options={
                'db_table': 'inventory_item_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryProductData',
            fields=[
                ('item_md_id', models.CharField(db_column='item_md_id', max_length=255, primary_key=True, serialize=False)),
                ('stock_on_order', models.IntegerField(blank=True, db_column='stock_on_order', null=True)),
                ('stock_committed', models.IntegerField(blank=True, db_column='stock_committed', null=True)),
            ],
            options={
                'db_table': 'inventory_product_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='InventoryItemMasterData',
        ),
    ]
